### PR TITLE
Update supported os

### PR DESCRIPTION
**Pull request by ketank-ibm**
Added support for Linux on Z(s390x)

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @ketank-ibm

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by ketank-ibm** [comment]
Our change change above shows to be merged but the cook book does not reflect in chef-supermarked zlinux category
can we know the reason why

**Comment by nkadel-skyhook** [comment]
There's a time lag between getting accepted to a git "master" and when the next tag gets created and published to the supermarket, for almost all chef cookbooks.

**Comment by tas50** [comment]
In general we're publishing to supermarket when any new features are added.  Supermarket metadata updates don't cross that line though so we held off on pushing new versions for these metadata updates.

**Comment by ketank-new** [comment]
Hi ,

I would like to know,if  there is a Continuous Integration setup for cookbooks
if yes than how can we make s390x part of the CI setup

Regards
Ketan

**Pull request merged**
