### PR TITLE
Adding support for user homedir deletion #137

### PR DESCRIPTION
**Pull request by anshulpatel25**
### Description

The change gives the capability to manage home directory upon user creation and deletion

### Issues Resolved

It resolves Issue #137

### CODE REVIEW

**Comment by tas50** [comment]
@anshulpatel25 Did you confirm that manage home actually deletes the directory when set to true?

**Comment by anshulpatel25** [comment]
Hi @tas50, 
I did verify it. It just relays call to user cookbook (https://docs.chef.io/resource_user.html)

**Comment by jamesdehart** [comment]
@anshulpatel25 could you please resolve the conflicts so that this can be merged? I would love this feature.

**Comment by anshulpatel25** [comment]
Closing this as new PR #426 now resolves the conflict.

CC: @tas50, @jamesdehart

**Pull request closed without merging**
