### PR TITLE
Allow to override base_homedir in users_manage

### PR DESCRIPTION
**Pull request by kesor**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @kesor

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by nkadel-skyhook** [comment]
Shouldn't this be accompanied by documentation changes?

**Comment by iennae** [comment]
This seems like a great option to add to the resource. Since it's been almost a year since creation, I'm not going to assume that you are still using this though. This PR requires a few things in order to get accepted.

1. You need to sign the CLA in order for us to accept the change.
2. Update your repository to the current state of the repo.
3. Update the README to include information about the home_basedir and example usage. 

Extra bonus points if you also:

4. create unit and integration tests for this. 

If you do the first 3, I will get this into a release quickly as it is a very straightforward change with little impact.

Thanks!

Jennifer

**Comment by iennae** [comment]
Closing as no response. If you want to take a look at my previous comment, and implement the changes suggested to reopen this totally open to your contributions. Thank you!

**Pull request closed without merging**
