### PR TITLE
add support to control ssh logins in authorized_keys and commands to be ...

### PR DESCRIPTION
**Pull request by jespada**
This add support to restrict ssh login and command on authorized_keys file when using ssh_keys.

### CODE REVIEW

**Comment by CpuID** [comment]
@jespada did you want to try rebase against master and see if the Travis failures go away?

**Comment by jespada** [comment]
@CpuID sure!

**Comment by jespada** [comment]
@CpuID  Travis is happy now!! :)

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 2 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @matfrancs

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by CpuID** [comment]
@jespada closed without a merge...?

**Comment by jespada** [comment]
@CpuID Yeah, I opened this PR while ago when I was actively working on this cookbook, I don't longer maintain this development branch, and there are other ppl pushing change to it that I have no idea the reason of them, so if they want they should open a new PR, properly explaining the why's. is that ok?
Sorry for closing this with no explanation.
Thanks

**Pull request closed without merging**
