### PR TITLE
Don't fail if "users" data bag doesn't exist

### PR DESCRIPTION
**Pull request by FlorentFlament**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @FlorentFlament

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by StephenKing** [comment]
Hey, I've just once again stumbled upon this. Any other way to let the `users::sysadmins` recipe _not_ fail, if the test-kitchen suite does not have the `users` data bag?

Otherwise I'd be happy, if you could merge this.

**Comment by tas50** [comment]
@FlorentFlament If this is still a change you'd like to make please rebase the PR and I'll make sure to get it merged in.

**Comment by tas50** [comment]
I'm going to close this out since the change has diverged from master and we haven't heard back about a rebase. If this is still something you want to get merged in please open a new PR against the  current master state.

**Pull request closed without merging**
